Minor grammer changes
MangoRageBot/MangoBotPlugin pull request #22
Opened 2024-05-31 19:29 UTC by Asbestosstar

Make it so modrinth perfos bug only triggers when the perfos part is in the last line.
Update Early Window to Emphasis drivers 1st.

2024-05-31 19:43 UTC, PaintNinja requested changes
PR title ironically has bad grammar btw ;P

2024-05-31 19:43 UTC, PaintNinja commented on src/main/java/org/mangorage/mangobot/modules/logs/ModrinthBug.java
> +				message.reply("This is a common issue on Modrinth Theseus. Modrinth's launcher has been known to be problematic in some cases with Forge. If you need to download a Modrinth format modpack you can
- "it's" means "it is", you probably meant "its".
- Forge doesn't use any special format - it's deliberately designed to work with the format Minecraft's official launcher uses

2024-05-31 19:43 UTC, PaintNinja commented on src/main/java/org/mangorage/mangobot/modules/logs/EarlyWindow.java
> +						+ "If you are on an M1 Mac you should also make sure you are using an ARM version of Java not an Intel x64 one."+nl
M1 Macs won't trigger a crash with the early loading screen, regardless of Java arch.

2024-05-31 19:43 UTC, PaintNinja commented on src/main/java/org/mangorage/mangobot/modules/logs/EarlyWindow.java
> +						+ "Edit earlyWindowProvider to be earlyWindowProvider=\"none\"")
We shouldn't be mentioning this at all, it will be used as a first resort because it looks easier and best case it fixes the issue and has users run Forge on integrated graphics, which they will blame on Forge being laggy, worst case it also breaks mods that want to take advantage of newer OpenGL

2024-05-31 19:43 UTC, PaintNinja commented on src/main/java/org/mangorage/mangobot/modules/logs/EarlyWindow.java
> +						+ "This is in many cases caused by broken drivers. If you have a graphics card from NVIDIA, make sure you set MinecraftLauncher and all instances of Minecraft's javaw.exe files. If you do not h
Make sure you set them to do what?

2024-05-31 19:55 UTC, Asbestosstar commented on src/main/java/org/mangorage/mangobot/modules/logs/ModrinthBug.java
> +				message.reply("This is a common issue on Modrinth Theseus. Modrinth's launcher has been known to be problematic in some cases with Forge. If you need to download a Modrinth format modpack you can
i meant the modrinth modpack format

2024-05-31 19:57 UTC, Asbestosstar commented
updated these things

2024-10-06 18:42 UTC, PaintNinja approved these changes

2025-02-10 02:26 UTC, RealMangorage commented
Can you fix the conflicting changes please. then I can pull it in. 
Sorry

2025-03-07 04:14 UTC, closed without merging